# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# compile CXX with /usr/bin/clang++
CXX_DEFINES = -DERNIE_PROBE_MODEL_PACKAGE=1

CXX_INCLUDES = -I/home/mingshi/Project/AI/ernie-image-ncnn-vulkan/.worktrees/surpass-reference/src -I/home/mingshi/Project/AI/ernie-image-ncnn-vulkan/third_party/ncnn/src -I/home/mingshi/Project/AI/ernie-image-ncnn-vulkan/.worktrees/surpass-reference/build-dev/ncnn/src

CXX_FLAGS = -O3 -DNDEBUG -std=gnu++17 -fPIE -fopenmp=libomp

