# Pinned ncnn configuration and the reviewed layer inventory.
file(READ "${PROJECT_SOURCE_DIR}/sources.lock.json" sources_lock)
string(JSON ncnn_revision GET "${sources_lock}" ncnn revision)
if(NOT EXISTS "${ERNIE_NCNN_SOURCE_DIR}/src/net.h")
    message(FATAL_ERROR "Initialize ncnn with: git submodule update --init third_party/ncnn")
endif()

find_package(Git REQUIRED)
execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${ERNIE_NCNN_SOURCE_DIR}" rev-parse HEAD
    OUTPUT_VARIABLE actual_revision OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
if(NOT actual_revision STREQUAL ncnn_revision AND NOT ERNIE_ALLOW_UNPINNED_NCNN)
    message(FATAL_ERROR "ncnn revision differs from sources.lock.json: ${actual_revision}")
endif()

set(NCNN_VULKAN ${ERNIE_ENABLE_VULKAN} CACHE BOOL "" FORCE)
if(ERNIE_ENABLE_VULKAN)
    # Exact Vulkan allocation failures unwind to the component checkpoint.
    set(NCNN_DISABLE_EXCEPTION OFF CACHE BOOL "" FORCE)
endif()
set(NCNN_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(NCNN_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(NCNN_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(NCNN_BUILD_BENCHMARK OFF CACHE BOOL "" FORCE)
set(NCNN_INSTALL_SDK ${ERNIE_INSTALL_SDK} CACHE BOOL "" FORCE)
if(APPLE AND ERNIE_ENABLE_VULKAN)
    # Use the installed loader on macOS. The pinned simplevk fallback exports a
    # source-tree .tbd path and direct MoltenVK bypasses loader ICD selection.
    option(NCNN_SIMPLEVK "minimal in-house vulkan loader" OFF)
endif()
if(ERNIE_INSTALL_SDK)
    if(ERNIE_ENABLE_ALLOCATION_METRICS)
        message(FATAL_ERROR "Use a separate non-instrumented build for ERNIE_INSTALL_SDK")
    endif()
    if(NCNN_SHARED_LIB)
        message(FATAL_ERROR "The installed Ernie SDK currently requires NCNN_SHARED_LIB=OFF")
    endif()
    if(ERNIE_ENABLE_VULKAN AND NCNN_SYSTEM_GLSLANG)
        message(FATAL_ERROR "The relocatable Ernie SDK requires NCNN_SYSTEM_GLSLANG=OFF")
    endif()
    # ncnn exports its pinned shader compiler dependencies with its SDK.
    set(GLSLANG_ENABLE_INSTALL ON CACHE BOOL "" FORCE)
endif()
if(ERNIE_MINIMAL_NCNN)
    # RMSNorm Vulkan shares reduction shaders with LayerNorm.
    # Extend this list when new exported components require additional layers.
    file(STRINGS "${ERNIE_NCNN_SOURCE_DIR}/src/CMakeLists.txt" layer_lines REGEX "^ncnn_add_layer\\(")
    set(probe_layers input split cast packing flatten softmax gemm sdpa memorydata unaryop reduction binaryop reshape permute rmsnorm layernorm slice expanddims concat squeeze gelu convolution padding innerproduct swish crop groupnorm interp multiheadattention reorg batchnorm)
    foreach(layer_line IN LISTS layer_lines)
        string(REGEX REPLACE "^ncnn_add_layer\\(([A-Za-z0-9_]+).*" "\\1" layer_name "${layer_line}")
        string(TOLOWER "${layer_name}" layer_name)
        if(layer_name IN_LIST probe_layers)
            set(WITH_LAYER_${layer_name} ON CACHE BOOL "" FORCE)
        else()
            set(WITH_LAYER_${layer_name} OFF CACHE BOOL "" FORCE)
        endif()
    endforeach()
endif()
include("${CMAKE_CURRENT_LIST_DIR}/ErnieAllocationMetrics.cmake")
ernie_prepare_allocation_metrics("${ERNIE_NCNN_SOURCE_DIR}" ernie_ncnn_build_source)
add_subdirectory("${ernie_ncnn_build_source}" "${CMAKE_BINARY_DIR}/ncnn")
include("${CMAKE_CURRENT_LIST_DIR}/ErnieNcnnAllocator.cmake")
ernie_prepare_ncnn_allocator("${ernie_ncnn_build_source}")
include("${CMAKE_CURRENT_LIST_DIR}/ErnieNcnnFailures.cmake")
ernie_prepare_ncnn_failures("${ernie_ncnn_build_source}")
include("${CMAKE_CURRENT_LIST_DIR}/ErnieNcnnBf16Sdpa.cmake")
ernie_prepare_ncnn_bf16_sdpa("${ernie_ncnn_build_source}")
include("${CMAKE_CURRENT_LIST_DIR}/ErnieModelReader.cmake")
ernie_prepare_model_reader("${ernie_ncnn_build_source}")
ernie_attach_allocation_metrics()
