# Diagnostic-only, default OFF: original ncnn path and dependencies are untouched.
option(ERNIE_ENABLE_ALLOCATION_METRICS "Observe actual ncnn Vulkan memory allocations" OFF)
function(ernie_prepare_allocation_metrics source result)
    if(NOT ERNIE_ENABLE_ALLOCATION_METRICS)
        set(${result} "${source}" PARENT_SCOPE)
        return()
    endif()
    if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux" OR ANDROID)
        message(FATAL_ERROR "Allocation instrumentation is reviewed for Linux only")
    endif()
    if(NCNN_PYTHON)
        message(FATAL_ERROR "Instrumented source export excludes optional pybind11/Python")
    endif()
    if(NOT ERNIE_ENABLE_VULKAN)
        message(FATAL_ERROR "Allocation instrumentation requires Vulkan")
    endif()
    find_package(Python3 COMPONENTS Interpreter REQUIRED)
    set(derived "${CMAKE_BINARY_DIR}/allocation-metrics-ncnn")
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/derive_allocation_ncnn.py"
        "${source}" "${derived}" COMMAND_ERROR_IS_FATAL ANY)
    add_library(ernie-allocation-metrics STATIC
        "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../src/allocation_metrics_hook.cpp")
    target_compile_features(ernie-allocation-metrics PUBLIC cxx_std_17)
    target_compile_definitions(ernie-allocation-metrics PRIVATE ERNIE_ALLOCATION_HOOKS_ENABLED=1)
    target_include_directories(ernie-allocation-metrics PUBLIC "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../src")
    find_package(Threads REQUIRED)
    target_link_libraries(ernie-allocation-metrics PUBLIC ernie-execution-metrics Threads::Threads)
    set(${result} "${derived}" PARENT_SCOPE)
endfunction()
function(ernie_attach_allocation_metrics)
    if(ERNIE_ENABLE_ALLOCATION_METRICS)
        target_link_libraries(ncnn PRIVATE ernie-allocation-metrics)
        target_compile_features(ncnn PRIVATE cxx_std_17)
    endif()
endfunction()
