# Preserve upstream files and native pipeline caching while supporting row masks.
function(ernie_prepare_ncnn_broadcast source)
    if(NOT ERNIE_ENABLE_VULKAN)
        return()
    endif()
    find_package(Python3 COMPONENTS Interpreter REQUIRED)
    set(directory "${CMAKE_BINARY_DIR}/ncnn-broadcast-mask")
    set(previous "${CMAKE_BINARY_DIR}/ncnn-bf16-sdpa/sdpa_vulkan.cpp")
    set(script "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/derive_sdpa_broadcast.py")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
        "${script}" "${source}/src/gpu.cpp")
    foreach(shader sdpa_cross sdpa_cross_cm sdpa_fa sdpa_fa_cm)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
            "${source}/src/layer/vulkan/shader/${shader}.comp")
    endforeach()
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${script}"
        --source "${source}" --bf16-source "${previous}"
        --registry "${CMAKE_BINARY_DIR}/ncnn/src/layer_shader_spv_data.h"
        --output "${directory}" COMMAND_ERROR_IS_FATAL ANY)
    get_target_property(sources ncnn SOURCES)
    foreach(unit gpu sdpa_vulkan)
        set(updated)
        set(matches 0)
        foreach(entry IN LISTS sources)
            if((unit STREQUAL "gpu" AND (entry STREQUAL "gpu.cpp" OR entry STREQUAL "${source}/src/gpu.cpp"))
                OR (unit STREQUAL "sdpa_vulkan" AND entry STREQUAL "${previous}"))
                math(EXPR matches "${matches} + 1")
                list(APPEND updated "${directory}/${unit}.cpp")
            else()
                list(APPEND updated "${entry}")
            endif()
        endforeach()
        if(NOT matches EQUAL 1)
            message(FATAL_ERROR "Expected one ncnn ${unit} compilation unit for broadcast masks")
        endif()
        set(sources "${updated}")
    endforeach()
    set_property(TARGET ncnn PROPERTY SOURCES "${sources}")
endfunction()
